### PR TITLE
issue #8: make sure to update calendar events when chnaging due dates

### PR DESCRIPTION
**Pull request by dmitriim**

### CODE REVIEW

**Comment by cameron1729** [comment]
Thanks Dmitrii,

I can see that this bug happens because we explicitly set `duedate` to 0 in `coursemodule_definition_after_data` (which happens before assign tries to update the calendar), and then in `coursemodule_edit_post_actions` we manually update the DB to have the correct `duedate`. And this patch now updates the calendar as well. While this does fix the immediate problem, I'm not sure it's the best solution.

I saw there's some comments, but I don't have the full picture, so I can't really follow the reason for setting the `duedate` to 0. Why don't we just set it to the value of the `newdate` field we added, and allow moodle to process the form data as it normally would? Then we wouldn't have to worry about manually editing the DB and updating the calendar like that.

If we can't do that, then another option is to use `assign_update_instance` instead of manually manipulating the `duedate` field. Since `assign_update_instance` uses the assign class's internal API to properly update an assignment instance, the calendar will be updated.

I'm just a bit worried about how we circumvent mod_assign's API for update assignments with this plugin. If core add something to mod_assigns create/update process, there's still a chance this plugin could circumvent it. If we use the API then there's no chance of us ending up in this situation again.

Also, whichever fix we go for, I think we need to apply it to `cli/reset.php` as well.

**Comment by cameron1729** [comment]
Another minor thing I spotted, I think [this](https://github.com/catalyst/moodle-local_submissionrestict/blob/MOODLE_39_STABLE/classes/local/mod/assign.php#L381) should be using `self::NEW_DUEDATE_FORM_FIELD`, shouldn't it?

**Comment by dmitriim** [comment]
hi @cameron1729 
I have fixed the issues with missed hardcoded field name and pushed directly to MOODLE_39_STABLE. Good catch!

Regarding setting up duedate as 0. It's related to a validation in the form. As validation happens before we can change a value for submitted due date, then in case if it's disabled, but Allow submissions from is still enabled, then it could be a case when an old due date (that we can't change) is earlier then  Allow submissions from  date and then we would get an error event if a new due date field is disabled. I tried to stick with the same name of the field, but it didn't work out well for the same reason as validation happens earlier than we can mutate submitted values.

So the easiest way was to pretend that due date is disabled (set it to 0) and then manage the rest of the logic using a new form field and only recover duedate when everything is validated. 

Regarding saving due date as direct SQL. I was trying to avoid changing other data from the form and update only what we would like to update. Well, it didn't work pretty well. 

I can try to run assign_update_instance again in my custom form processor, however it'll mean to run all underlying updates again. Including events.  Also I'm not sure if $moduleinfo is the same as $data in assign_update_instance. That's why I run only $assign->update_calendar($cm->id) here.

**Comment by cameron1729** [comment]
Thanks Dmitrii, this new method seems a lot more robust.

The [cli script](https://github.com/catalyst/moodle-local_submissionrestict/blob/MOODLE_39_STABLE/cli/reset.php#L165) is still directly updating the assign table. If we run that won't we have the same problem? (i.e., assignments will have their duedate updated, but the corresponding calendar event will not be changed)?

**Comment by dmitriim** [comment]
@cameron1729 I have updated CLI script and also added upgrade hook to fixed all missing future events.

**Pull request merged**
